name: GHA

run-name: ${{ github.head_ref || github.ref_name }}-gha

on: # yamllint disable-line rule:truthy
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: gha-${{ github.event.number }}
  cancel-in-progress: true


jobs:
  gdlint:
    if: ${{ !cancelled() }}
    name: '📝 GDLint'
    uses: ./.github/workflows/gdlint.yml

  generation_testing:
    name: '🐞 Generation Testing'
    uses: ./.github/workflows/generation_testing.yml
    
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    
  nodes_testing:
    name: '🐞 Node Testing'
    uses: ./.github/workflows/nodes_testing.yml
    
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    
  renderers_testing:
    name: '🐞 Renderers Testing'
    uses: ./.github/workflows/renderers_testing.yml
    
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    

